version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 frontend:
  build: front
  restart: always
  ports:
  - "4200:4200"
  volumes:
  - ./front:/usr/src/app
  env_file:
  - .env
  
 backend: 
  build: back
  restart: always
  ports:
  - "3000:3000"
  depends_on:
  - database
  volumes:
  - ./back/:/usr/src/app
  env_file:
  - .env

 database:
  image: mongo
  ports:
  - "27017:27017"